# Generated by Django 3.2 on 2021-04-25 21:36
# noqa
import datetime
from django.db import migrations


def forward_func(apps, schema_editor):
    Student = apps.get_model("app", "Student")
    st1 = Student(first_name="Dmitry", last_name="S")
    st2 = Student(first_name="Ivan", last_name="Prusakov")
    st1.save(), st2.save()
    Teacher = apps.get_model("app", "Teacher")
    t1 = Teacher(first_name="Karl", last_name="Liebher")
    t2 = Teacher(first_name="Maksim", last_name="Pokrovsky")
    t1.save(), t2.save()
    Homework = apps.get_model("app", "Homework")
    hw1 = Homework(
        teacher=t1,
        text="Homework text 1",
        deadline=datetime.timedelta(days=4),
        create_date=datetime.datetime.now(),
    )
    hw2 = Homework(
        teacher=t2,
        text="Homework text 2",
        deadline=datetime.timedelta(days=0),
        create_date=datetime.datetime.now(),
    )
    hw1.save(), hw2.save()
    HomeworkResult = apps.get_model("app", "HomeworkResult")
    hw_res1 = HomeworkResult(
        homeworker=st1,
        task_text=hw1,
        solution="My good solution",
        end_time=datetime.datetime(
            year=2021, month=4, day=26, hour=10, minute=58, second=00
        ),
    )
    hw_res2 = HomeworkResult(
        homeworker=st2,
        task_text=hw1,
        solution="Bad solution",
        end_time=datetime.datetime(
            year=2021, month=4, day=26, hour=11, minute=13, second=00
        ),
    )
    hw_res1.save(), hw_res2.save()
    HomeworkDone = apps.get_model("app", "HomeworkDone")
    hwd = HomeworkDone(good_homework=hw_res1)
    hwd.save()


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(forward_func),
    ]
